# Generated by Django 4.2.2 on 2023-08-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0008_alter_class_academic_year_alter_class_grade_level"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_relation",
        ),
        migrations.AddField(
            model_name="student",
            name="class_relation",
            field=models.ManyToManyField(to="classes.class"),
        ),
    ]
