# Generated by Django 4.2.2 on 2023-08-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0008_alter_class_academic_year_alter_class_grade_level"),
        ("students", "0002_remove_student_class_relation_student_class_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="class_relation",
        ),
        migrations.AddField(
            model_name="student",
            name="class_relation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
            ),
            preserve_default=False,
        ),
    ]
