# Generated by Django 4.2.2 on 2023-08-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0008_alter_class_academic_year_alter_class_grade_level"),
        ("students", "0003_remove_student_class_relation_student_class_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_relation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
            ),
        ),
    ]
