# Generated by Django 4.2.2 on 2024-06-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("academic_year", models.IntegerField(blank=True, null=True)),
                ("grade_level", models.CharField(blank=True, max_length=10, null=True)),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "homeroom_teacher",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "subject_combination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("class_capacity", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "class_schedule",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("room_number", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
