# Generated by Django 4.2.2 on 2023-08-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_teacher_test_field"),
        ("classes", "0002_class_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="teacher",
        ),
        migrations.AddField(
            model_name="class",
            name="teacher",
            field=models.ManyToManyField(to="accounts.teacher"),
        ),
    ]
