# Generated by Django 4.2.2 on 2023-08-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_remove_class_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="academic_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="grade_level",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
