# Generated by Django 4.2.2 on 2023-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="approve",
            field=models.BooleanField(default=False),
        ),
    ]
