# Generated by Django 4.2.2 on 2023-07-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_birth_date_customuser_birthday_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthday_date",
            field=models.DateField(help_text="yyyy-mm-dd"),
        ),
    ]
