# Generated by Django 4.2.2 on 2023-07-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthday_date",
            field=models.DateField(blank=True, help_text="yyyy-mm-dd", null=True),
        ),
    ]
