# Generated by Django 4.2.2 on 2023-07-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_approve"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="approve",
            field=models.BooleanField(default=False),
        ),
    ]
