# Generated by Django 4.2.2 on 2023-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_birthday_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("TEACHER", "Teacher"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
    ]
