# Generated by Django 4.2.2 on 2023-08-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_teacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
