# Generated by Django 4.2.2 on 2023-08-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_teacher_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="test_field",
        ),
    ]
