# Generated by Django 4.2.2 on 2023-08-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_remove_class_teacher"),
        ("accounts", "0015_remove_teacher_class_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="class_relation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.class",
            ),
            preserve_default=False,
        ),
    ]
