# Generated by Django 4.2.2 on 2023-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0008_alter_class_academic_year_alter_class_grade_level"),
        ("accounts", "0016_teacher_class_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="class_relation",
        ),
        migrations.AddField(
            model_name="teacher",
            name="class_relation",
            field=models.ManyToManyField(to="classes.class"),
        ),
    ]
