# Generated by Django 4.2.2 on 2023-08-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_teacher_class_relation_teacher_class_relation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
