# Generated by Django 4.2.2 on 2023-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_delete_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="approve",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
