# Generated by Django 4.2.2 on 2024-01-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_customuser_approve_customuser_is_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_approved",
            new_name="approved",
        ),
    ]
