# Generated by Django 4.2.2 on 2023-08-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
