# Generated by Django 4.2.2 on 2024-01-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_request", "0003_rename_is_approved_leaverequest_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="approved",
        ),
    ]
