# Generated by Django 4.2.2 on 2023-07-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
