# Generated by Django 4.2.2 on 2023-07-15 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_course_name"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
